#!/bin/sh

set -e
set -x

if [ -z $ANDROID_HOME ]; then
    if [ -e ~/.android/bashrc ]; then
        . ~/.android/bashrc
    else
        echo "ANDROID_HOME must be set!"
        exit
    fi
fi

git submodule sync --recursive
git submodule foreach --recursive "git submodule sync"
git submodule update --init --recursive

export TZ=UTC
TIMESTAMP=`git log -n1 --format=format:%ai`

# reset version code/name to current date
versionCodeDate=`faketime "$TIMESTAMP" date +%s`
versionNameDate=`faketime "$TIMESTAMP" date +%Y-%m-%d_%H.%M.%S`

sed -i \
    -e "s,android:versionCode=\"[0-9][0-9]*\",android:versionCode=\"$versionCodeDate\"," \
    -e "s,android:versionName=\"\([^\"][^\"]*\)\",android:versionName=\"\1.$versionNameDate\"," \
    AndroidManifest.xml

make -C external/ clean
make -C external/ assets

# build gnupg and move **FIXME** (godlessfather stinks at Makefile syntax)
cd external/gnupg
./autogen.sh --force
CFLAGS="-static" ./configure --host=arm-linux-gnueabi --enable-maintainer-mode
make
cp g10/gpgv $projectroot/assets/
# end **FIXME**
./setup-ant

./tests/run-tests
